name: GHA_firstworkflow
on: workflow_dispatch
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: print greetings
              run: echo "Hello world"
            - name: print goodbye
              run: |
                echo "This is my first GHA"
                echo "workflow execuited successfully"
