name: Push_workflow
on:
    push:
        branches:
            - main
            - dev
    pull_request:
        branches:
            - main
            - release-*
    workflow_dispatch:
    # schedule:
    #     - cron: "0 9 * * *"
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: print greetings
              run: echo "Hello world"
            - name: print goodbye
              run: |
                echo "This is my first GHA"
                echo "workflow execuited successfully"
